VALID_RECEPTACLES = {
    "AlarmClock" : ["Box", "Desk", "SideTable", "DiningTable", "CoffeeTable", "CounterTop", "Shelf", "Floor"],
    "Apple" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "GarbageCan", "Floor"],
    "AppleSliced" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "GarbageCan", "Floor"],
    "BaseballBat" : ["Bed", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "Floor"],
    "BasketBall" : ["Sofa", "ArmChair", "Desk", "Bed", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Floor"],
    "Book" : ["Sofa", "ArmChair", "Box", "Ottoman", "Desk", "Bed", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Floor"],
    "Bottle" : ["Fridge", "Box", "Desk", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "GarbageCan", "Floor"],
    "Bowl" : ["Microwave", "Fridge", "Desk", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Floor"],
    "Box" : ["Sofa", "ArmChair", "Desk", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Ottoman", "Floor"],
    "Bread" : ["Microwave", "Fridge", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "GarbageCan", "Plate", "Floor"],
    "BreadSliced" : ["Microwave", "Fridge", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "GarbageCan", "Plate", "Floor"],
    "ButterKnife" : ["Pot", "Pan", "Bowl", "Mug", "Plate", "Cup", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "Desk", "CounterTop", "Drawer", "Floor"],
    "Candle" : ["Box", "Desk", "Toilet", "Cart", "Bathtub", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Floor"],
    "CD" : ["Box", "Ottoman", "Desk", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Safe", "Sofa", "ArmChair", "Floor"],
    "CellPhone" : ["Sofa", "ArmChair", "Box", "Ottoman", "Desk", "Bed", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Safe", "Floor"],
    "Cloth" : ["Sofa", "ArmChair", "Box", "Ottoman", "LaundryHamper", "Desk", "Toilet", "Cart", "BathtubBasin", "Bathtub", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "CreditCard" : ["Sofa", "ArmChair", "Box", "Ottoman", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Shelf", "Floor"],
    "Cup" : ["Microwave", "Fridge", "Desk", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Floor"],
    "DishSponge" : ["Pot", "Pan", "Bowl", "Plate", "Box", "Toilet", "Cart", "Cart", "BathtubBasin", "Bathtub", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Egg" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "EggCracked" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "Fork" : ["Pot", "Pan", "Bowl", "Mug", "Plate", "Cup", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Floor"],
    "HandTowel" : ["HandTowelHolder", "Floor"],
    "Kettle" : ["DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Sink", "SinkBasin", "Cabinet", "StoveBurner", "Shelf", "Floor"],
    "KeyChain" : ["Sofa", "ArmChair", "Box", "Ottoman", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Safe", "Floor"],
    "Knife" : ["Pot", "Pan", "Bowl", "Mug", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Floor"],
    "Ladle" : ["Pot", "Pan", "Bowl", "Plate", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Floor"],
    "Laptop" : ["Sofa", "ArmChair", "Ottoman", "Desk", "Bed", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Floor"],
    "Lettuce" : ["Pot", "Pan", "Bowl", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "LettuceSliced" : ["Pot", "Pan", "Bowl", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "Mug" : ["SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Floor"],
    "Newspaper" : ["Sofa", "ArmChair", "Ottoman", "Desk", "Bed", "Toilet", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Pan" : ["DiningTable", "CounterTop", "CoffeeTable", "SideTable", "Sink", "SinkBasin", "Cabinet", "StoveBurner", "Fridge", "Floor"],
    "Pen" : ["Mug", "Box", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Pencil" : ["Mug", "Box", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "PepperShaker" : ["DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Cabinet", "Shelf", "Floor"],
    "Pillow" : ["Sofa", "ArmChair", "Ottoman", "Bed", "Floor"],
    "Plate" : ["Microwave", "Fridge", "Desk", "Sink", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Floor"],
    "Plunger" : ["Cart", "Cabinet", "Floor"],
    "Pot" : ["StoveBurner", "Fridge", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Floor"],
    "Potato" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "PotatoSliced" : ["Pot", "Pan", "Bowl", "Microwave", "Fridge", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "GarbageCan", "Floor"],
    "RemoteControl" : ["Sofa", "ArmChair", "Box", "Ottoman", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Floor"],
    "SaltShaker" : ["DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Cabinet", "Shelf", "Floor"],
    "SoapBar" : ["Toilet", "Cart", "Bathtub", "BathtubBasin", "Sink", "SinkBasin", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "SoapBottle" : ["Desk", "Toilet", "Cart", "Bathtub", "Sink", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Spatula" : ["Pot", "Pan", "Bowl", "Plate", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Floor"],
    "Spoon" : ["Pot", "Pan", "Bowl", "Mug", "Plate", "Cup", "Sink", "SinkBasin", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Drawer", "Floor"],
    "SprayBottle" : ["Desk", "Toilet", "Cart", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Statue" : ["Box", "Desk", "Cart", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Safe", "Floor"],
    "TeddyBear" : ["Bed", "Sofa", "ArmChair", "Ottoman", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Safe", "Floor"],
    "TennisRacket" : ["Desk", "Bed", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Floor"],
    "TissueBox" : ["Box", "Desk", "Toilet", "Cart", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "ToiletPaper" : ["Desk", "Toilet", "ToiletPaperHanger", "Cart", "Bathtub", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "GarbageCan", "Floor"],
    "Tomato" : ["DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Sink", "SinkBasin", "Pot", "Bowl", "Fridge", "GarbageCan", "Plate", "Floor"],
    "TomatoSliced" : ["DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Sink", "SinkBasin", "Pot", "Bowl", "Fridge", "GarbageCan", "Plate", "Floor"],
    "Towel" : ["TowelHolder", "Floor"],
    "Vase" : ["Box", "Desk", "Cart", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Safe", "Floor"],
    "Watch" : ["Box", "Desk", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Safe", "Floor"],
    "WateringCan" : ["Desk", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "Drawer", "Floor"],
    "WineBottle" : ["Fridge", "Desk", "Cabinet", "DiningTable", "CoffeeTable", "SideTable", "CounterTop", "Shelf", "GarbageCan", "Floor"]
}